### ISSUE TITLE
**New Maintainer Wanted**

### ISSUE THREAD

**Issue by claviska** [soundasleep/jquery-dropdown#128]
This was a fun project while it lasted, but I no longer have time to commit to maintaining it. If you're up for adopting it, please let me know below.

If you're looking for simpler dropdowns, consider checking out my project [Shoelace.css](https://shoelace.style). It's a lightweight, forward-thinking CSS starter kit that has a number of helpful components, including dropdowns.

**Comment by soundasleep** [comment]
I'm impressed with your project, I would be happy to put my hand up for maintaining! :)

**Comment by claviska** [comment]
And so it was. Thanks for volunteering!

**Comment by soundasleep** [comment]
My pleasure ^_^
